---
- name: install pritunl repo
  template:
    src: pritunl.rhel.repo.j2
    dest: /etc/yum.repos.d/pritunl.repo

- name: install pritunl gpg key
  rpm_key:
    state: present
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7AE645C0CF8E292A

- name: install mongo-db repo
  template:
    src: mongodb.rhel.repo.j2
    dest: "/etc/yum.repos.d/mongodb-org-{{ mongo_version }}.repo"

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install pritunl and dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - mongodb-org
    - openvpn
    - pritunl

- name: start pritunl services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - pritunl
    - mongod
