---
- name: setup gateway apps
  hosts: gateways
  become: true
  pre_tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ gateway_packages }}"
    - name: "create {{ ansible_run_flag }}"
      template:
        src: ansible.run
        dest: "{{ ansible_run_flag }}"
  roles:
    - generic-host
    - pritunl
